### ISSUE TITLE
یاکوب

### ISSUE THREAD

**Issue by AmirYousofAbdi** [AmirYousofAbdi/Stock_Forecast#19]
سلام آقای معصومی
 من اومدم یه تلفیقی از یاکوب و خودم بزنم ولی یه ارور خیلی عجیب میده کدشم هم گذاشتم به نام پرابلم و وقتی ارورش رو خوندم, ظاهرا میشگه تابع 
fit() 
حداکثر با دو بعد کار میکنه.
تنسرفلو هم نتونستم نصب کنم ولی رفتم کدشو که دیدم فقط یه جا ازش استفاده کرده که میگه
set_random_seed(4)
بنظرتون قسمت مهمی هستش؟
و تا هفته بعد تا سر the training اماده میکنم بهتون میدم
بعد میشه لطفا 28 خط اول
https://github.com/yacoubb/stock-trading-ml/blob/master/basic_model.py
رو توضیح بدین لطفا
با تشکر

**Comment by AmirYousofAbdi** [comment]
و همون لینک بخش تکامل(evaluation) رو میشه توضیح بدین
در مورد مت پلات لیبش هم, چرا 
start/end 
رو گذاشته 0 و -1؟
با تشکر

**Comment by AmirYousofAbdi** [comment]
سلام
میشه لطفا بگین برای رفع اشکل کد زیر باید چیکار کنم؟
خیلی تو اینترنت گشتم و کلی کار کردم ولی نشد.
`import keras
`
ارور:
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\p1.py", line 1, in <module>
    import keras
  File "C:\Users\Lenovo\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Lenovo\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Lenovo\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Lenovo\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Lenovo\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Lenovo\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Lenovo\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\Lenovo\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Lenovo\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Lenovo\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Lenovo\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Lenovo\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\Lenovo\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\Lenovo\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by AmirYousofAbdi** [comment]
خوندم که میگفت نمیدونم باید 
cuda(v:9) / cudnn 
نصب کنم. ولی اصلا نمیدونم اینا چین
